version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./target/indigoBuild:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf